export { authRoutes } from './auth.js'
export { usersRoutes } from './users.js'
export { supervisorsRoutes } from './supervisors.js'
export { projectsRoutes } from './projects.js'
export { timesheetsRoutes } from './timesheets.js'
export { approvalsRoutes } from './approvals.js'
export { notificationsRoutes } from './notifications.js'
export { activitiesRoutes } from './activities.js'
export { documentsRoutes, myDocumentsRoutes } from './documents.js'
export { reportsRoutes } from './reports.js'
export { settingsRoutes } from './settings.js'
